package com.example.serialkiller;

import java.util.ArrayList;

public class KillersData {

    private static  String[] detailPem = {
            "\t\tAhmad Suradji adalah seorang pembunuh berantai Indonesia yang masuk ke dalam deretan \"serial killer\" dunia, ia di perhitungkan karena korbannya yang sangat banyak, yaitu mencapai 42 orang serta alasan pembunuhan yang cukup unik dan perkaitan dengan hal mistis yang di percayai oleh masyarakat yang ada di desanya.\n"+ "" +
                    "\t\tPada waktu kecil, ia pernah tercebur ke sumur dan hampir tewas, setelah selamat banyak kenalan dan para tetangganya yang memanggilnya dengan sebutan \"Nasib\" karena keberuntungannya selamat dari maut tersebut.",
            "\t\tHampir semua anggota keluarga Albert memiliki riwayat penyakit kejiwaan yang sangat kental. Ayahnya meninggal karena serangan jantung pada tanggal 16 Oktober 1875 ketika Albert berusia 5 tahun. Setelah kepergiaan Ayahnya, Albert dimasukkan ke panti asuhan Saint John di Washington oleh Ibunya, dengan alasan tidak dapat menghidupinya. Ditempat tersebut, Albert seringkali mendapat pelecehan, pemukulan dan juga kekerasan fisik, bahkan tidak jarang sesama penghuni panti asuhan tersebut \"di paksa\" untuk saling menyakiti. Namun Anehnya setelah sering mengalami hal tersebut, Albert menyatakan bahwa ia mulai menikmati rasa sakit dari tindak kekerasan tersebut, ini adalah awal dimana Albert memunculkan ciri Sadomakosisme atau kenikmatan seksual yang ia dapatkan dari kekerasan ataupun penyiksaan.\n"+
                    "\t\tPada tahun 1880, Albert keluar dari panti asuhan setelah Ibunya berhasil mendapatkan pekerjaan di pemerintahan. Kemudian pada usia 12 tahun, Albert mulai berkenalan dan bergaul dengan seorang remaja lain yang bekerja sebagai pengantar telegraph. Ia kemudian di perkenalkan dengan berbagai tindakan yang aneh seperti urolagnia (meminum urine) dan coprophagia (memakan kotoran).\n"+
                    "\t\tAlbert juga sering mengunjungi pemandian umum diakhir minggu, hanya untuk melihat anak laki-laki yang telanjang, ia juga mulai menuliskan banyak surat-surat \"berbau seksual\" kepada para wanita yang namanya ia dapatkan dari surat kabar."+
                    "\t\tDalam akhir persidangan, Albert dinyatakan waras dan bersalah atas sejumlah pembunuhan, mutilasi dan perbuatan kejam lainnya. Hakim memutuskan hukuman mati yang dilakukan pada tanggal 16 Januari 1936. Albert sempat berkata bahwa \"Listrik adalah sensasi tertinggi dalam hidupku.\"",
            "\t\tKakek buyutnya adalah Stephen Báthory of Somlyó, salah satu kesatria yang turut berjuang bersama Vlad The Impaler atau Vlad Dracul, seorang penguasa Romania yang merupakan inspirasi dari tokoh \"Dracula\" yang sesungguhnya, Elizabeth hidup kurang lebih 100 tahun setelah Vlad Dracul meninggal. Kekejamannya juga sering di bandingkan dengan Vlad Dracul dan keduanya adalah inspirasi dari Novel \"Dracula\" yang terbit di 1897.\n"+
                    "\t\tKetika kecil Elizabeth banyak menderita kejang akibat epilepsi, ada asumsi yang menyatakan bahwa ia lahir dari pekawinan sejarah dan itulah yang menjadi sumber masalah kesehatannya. Elizabeth yang menghabiskan masa kecilnya di kastil kerjaan, ia dikenal sebagai seorang anak yang pemarah dan juga manja, ia juga sering berlaku kasar namun tidak pernah ada yang berani memprotes kelakuannya",
            "\t\tTerlahir dengan nama Harold Frederick Shipman, Harold lahir di Nottingham, Inggris dan merupakan anak keduadari empat bersaudara. Ayahnya berprofesi sebagai seorang pengemudi Truk dan Ibunya adalah seorang Ibu Rumah Tangga. Kedua orangtuanya adalah penganut Agama yang taat.\n"+
                    "\t\tPada awal karirnya Harold di kenal sebagai dokter umum yang banyak menangani kesehatan keluarga, namun pada tahun 1975 ketika ia sudah memiliki dua orang anak, ia mencoba dan menjadi kecanduan terhadap salah satu obat penghilang rasa sakit. Hal ini di duga sebagai upayanya untuk mengeksplorasi dampak morfin dan zat sejenis yang di berikan pada Ibunya ketika meninggal dunia, karena salah satu alasannya menekuni dunia kedokteran adalah ketertarikannya dengan hal tersebut.\n"+
                    "\t\tHarold kemudian di deteksi serta terbukti memalsukan resep Demerol (Sejenis Obat Penenang) untuk penggunaan pribadi, ia kemudian terpaksa keluar sementara dari praktik kedokterannya, ia kemudian mendapatkan hukuman denda dan harus mengikuti rehabilitasi narkoba, namun setelahnya ia masih di izinkan untuk meneruskan profesinya sebagai seorang dokter.\n"+
                    "\t\tKorban terakhir Harold, Kathleen Grundy adalah kunci bagaimana semua kejahatannya pada akhirnya berhasil terungkap. Hal ini di sebabkan Putri dari Kathleen menaruh kecurigaan terhadap surat wasiat ibunya yang menyatakan menyerahkan sebagian besar harta warisannya atau sekitar 40.000 Euro kepada Harold, bukan kepada anak-anaknya.\n"+
                    "\t\tAkhirnya berdasarkan kesepakatan keluarga, makam Kathleen di bongkar dan tubuhnya di otopsi dan di temukan bahwa ada kandungan diamorfin (obat penghilang rasa sakit) dalam kandungan besar yang menyebabkan kematiannya, pada awalnya Harold beralasan hal tersebut di berikan untuk menghilangkan rasa sakit dan meringankan beban Kathleen, ia juga mengaku sebagai seorang pecandu dari obat yang di berikannya tersebut. Namun karena kemudian di temukan mesin tik, alat dalam membuat surat wasiat palsu dan ada juga indikasi dari rekayasa catatan medis, Harold di nyatakan harus menjalani periksaan lebih lanjut. Dalam pemeriksaan Polisi juga menemukan banyak sertifikat kematian yang di tanda tanganinya dengan alasan kematian yang mencurigakan.",
            "\t\tSelama kurang lebih 18 bulan, pria bernama Javed Iqbal telah menghabisi setidaknya 100 anak laki-laki dengan sangat keji.\n"+
                    "\t\tTidak ada yang aneh dari kehidupan seorang Javed Iqbal saat kecil. Lahir di Lahore, Pakistan pada tahun 1956, Javed menjalani kehidupan dengan normal. Ayahnya adalah seorang pebisnis andal sehingga untuk masalah finansial, Javed tidak pernah kebingungan. Di Pakistan dia sekolah di perguruan tinggi Islam hingga akhirnya lulus\n"+
                    "\t\tSaat masih bersekolah pada tahun 1978, Javed sudah memulai bisnis. Berkat didikan dari ayahnya dia mulai membuat bisnis di bidang pengolahan baja. Selama menjalani bisnis, Javed mulai pindah ke sebuah vila di Shadbagh dengan seorang pria. Dari sini kisahnya menjadi penuh rahasia dan tidak diketahui hingga berita mengerikan tentang pembunuhan 100 anak laki-laki mencuat.\n"+
                    "\t\tKejahatan dari seorang Javed terungkap setelah dua mayat anak laki-laki ditemukan dengan keadaan yang mengerikan. Tubuhnya terpotong-potong dan dimasukkan ke dalam sebuah kotak lalu diberi larutan hydrochlorid acid. Larutan ini bersifat korosif sehingga apa saja yang dimasukkan ke dalamnya akan hancur ke dalam sekejap termasuk mayat dari dua anak laki-laki itu.\n"+
                    "\t\tSetelah mayat dari dua anak itu hancur, Javed akan membuangnya ke saluran pembuangan. Dari sini dia merasa sudah mampu menghilangkan barang bukti. Metode super ngeri ini dilakukan berkali-kali oleh Javed hingga akhirnya dia merasa ketakutan dan takut akan ditangkap oleh polisi lalu dihabisi."+
                    "\t\tSebagai orang yang kaya, Javed bisa melakukan apa saja yang dia mau termasuk mencari anak-anak dengan jenis kelamin laki-laki. Biasanya dia akan mencarinya di jalanan atau ke kawasan di mana penduduknya berada pada strata ekonomi rendah. Setelah sampai rumah mereka akan diminumi obat hingga teler. Setelah anak laki-laki itu tidak begitu sadar, Javed akan melakukan tindakan asusila sembari menyiksanya sampai puas. Kalau semua keinginannya sudah tercapai, anak itu akan langsung dihabisi.\n"+
                    "\t\tDi pengadilan, Javed dinyatakan bersalah dan mendapatkan hukuman mati. Dia terbukti melakukan pembunuhan berantai dengan motif kekerasan dan kejahatan seksual. Untuk aksinya ini, dia dianugerahi hukuman mati meski pada akhirnya dia bunuh diri di dalam sel tahanannya karena takut akan digantung",
            "\t\tJohn Wayne Gacy adalah seorang anak yang tumbuh dengan penuh tekanan, ia lahir dengan darah Polandia dan Denmark, memiliki seorang ayah pecandu alkohol berat yang seringkali melakukan tindakan kekerasan seperti pemukulan terhadap dirinya, saudara kandung dan ibunya."+
                    "\t\tDalam berbagai wawancara, Gacy menyatakan bahwa Ayahnya sering memanggilnya dengan sebutan \"Bodoh\", memukulnya dengan sabuk kulit, ia berusaha tidak pernah menangis ketika menerima setiap pukulan, bahkan pernah suatu ketika ia tertangkap melakukan kenakalan saat masih kecil, ia di pukul hingga pingsan oleh ayahnya, ibunya kemudian berusaha untuk melindunginya, namun ia malah mendapatkan julukan \"Anak Mami\" dan \"Banci\" karena di bela oleh Ibunya.\n"+
                    "\t\tSejak kecil, Gacy memiliki badan yang gemuk dan kondisi jatung yang lemah, sehingga tidak bisa banyak melakukan kegiatan fisik, terutama olahraga, ia juga sering pingsan dan di rawat di rumah sakit, awalnya ayahnya mengira Gacy berpura-pura untuk mendapatkan simpati, barulah setelah bertahun-tahun kemudian barulah terungkap bahwa ada gumpalan darah di otak akibat pemukulan yang di lakukan oleh Ayahnya. Ia juga seringkali menjadi korban bully tanpa alasan, dari keterangan beberapa temannya saat itu, Gacy menjadi korban Bullying karena tidak pernah melakukan perlawanan."+
                    "\t\tGacy juga pernah mendapatkan pelecehan seksual dari teman ayahnya, namun ia tidak pernah beritahukan kepada siapapun, karena takut kena hukuman. Barulah ketika ia menjalani pemeriksaan psikologis saat dewasa hal ini terdeteksi. Menurut beberapa profiler Ini adalah salah satu moment awal yang menjadikan Gacy seorang Biseksual."+
                    "\t\tSelain Trauma di lecehkan ketika kecil dan pengalaman membelai mayat ketika bekerja di ambulance, Gacy menyatakan pernah mengalami pengalaman hubungan sesama jenis ketika sedang mabuk, ia melakukan hubungan tersebut bersam dengan rekannya di salah satu organisasi sosial yang di ikutinya."+
                    "\t\tPada tanggal 11 Desember 1978, Seorang pemuda bernama Robert Jerome Piest dilaporkan hilang. Ia terakhir kali berbicara dengan Gacy mengenai pekerjaan renovasi sebuah apotek lalu kemudian tidak pernah kembali. Polisi kemudian melakukan penyelidikan, walaupun Gacy menyangkal semua tuduhan, Polisi tetap menaruh curiga apalagi melihat catatan kriminal Gacy yang pernah terlibat dalam kasus pelecehan seksual terhadap remaja pria. Polisi sempat melakukan penggeledahan, menemukan beberapa bukti, tapi tidak cukup kuat untuk menjerat Gacy ke dalam tudahan yang serius."+
                    "\t\tDetektif yang menangani Gacy juga mendapatkan banyak laporan Pemuda yang hilan  dengan profile yang sama, yaitu pernah terlibat dalam pekerjaan dengan Gacy, setelah mendapatkan beberapa keterangan saksi dan bukti cukup kuat, akhirnya penggeledahan yang kedua di lakukan. Berbeda dengan penggeledahan pertama dimana suasana rumah dingin, kali ini suasana yang cukup panas memunculkan beberapa bau busuk yang berasal dari bawah lantai rumah. Akhirnya Polisi menggali bagian bawah rumahnya dan menemukan mayat korban pembunuhan yang di lakukan oleh Gacy.\n"+
                    "\t\tGacy kemudian sadar bahwa penangkapannya tidak bisa di hindari, ia juga sempat mengaku kepada pengacaranya sehari sebelum penangkapan bahwa ia telah melakukan setidaknya 30 pembunuhan. Selama jam terakhir kebebasannya, Gacy sempat mengunjungi beberapa teman dekat untuk mengucapkan salam perpisahan, ia juga di duga sempat ingin melakukan tindakan bunuh diri sebelum pada akhirnya di tangkap oleh Polisi untuk di amankan.",
            "\t\tLuis Garavito terlahir di keluarga tak harmonis dengan status sulung dengan enam adik. Seluruh saudara ini mengalami masa-masa yang suram akibat ayah mereka yang alkoholik dan sudah menyiksa Luis Garavito baik secara fisik maupun seksual sejak kecil, atau setidaknya demikianlah pengakuannya saat tertangkap. Sementara ibunya diperkirakan adalah seorang pelacur. Ayahnya memaksa ia melihat ibunya saat bekerja an mengizinkan pelanggan ibunya untuk juga melecehkannya secara seksual. Umur 8 tahun, ia diimingi makanan hangat dan tempat menginap yang nyaman oleh seorang asing. Orang tersebut ternyata menipunya dengan membawa ke sebuah gedung kosong dan memperkosanya. Beberapa hari kemudian, ia direkrut gang pemberontak untuk mendapatkan perlindungan. Gang ini sering merampok rakyat Kolombia. Umur 16 tahun, ia lari dari rumah untuk hidup terpisah dari ayahnya. Untuk mencari penghidupan, ia jarus berkeliling Kolombia. Ia mulai menjadi juru catat di toko sebelum akhirnya menjadi pedagang kaki lima yang menjual kartu doa dan patung relijius lainnya. Meskipun terus bertualang, ia sempat memiliki kekasih dan seorang anak. Teman-temannya memberikan kesaksian bahwa ia orang yang baik meskipun pemarah.\n"+
                    "\t\tSaat sudah dewasa, ia meneruskan kebiasaan alkoholik dari ayahnya, sambil terus berkelana dari kota ke kota untuk mencari kerja. Ia juga memelihara kebiasaan berkelahi sehingga selalu diusir dari lingkungan tempat tinggalnya. Menurut catatan polisi, ia juga pernah berusaha bunuh diri.\n"+
                    "\t\tDiperkirakan Garavito memulai kebiasaan jahatnya sejak tahun 1992. Ia selalu selektif memilih korban, biasanya yang dicari usia 6-12 tahun, dengan latar belakang spesifik, anak yatim, miskin atau gelandangan. Ia tahu anak-anak ini bermasalah dan tidak akan ada yang mencari mereka bila menghilang. Biasanya ia akan mendekati mereka di daerah pinggiran, namun kadang ia juga menemui mereka di jalanan ramai. Kebanyakan dari mereka diimingi hadiah atau uang. Kadang ia menawari pekerjaan. Untuk menumbuhkan kepercayaan dari calon korban, ia menyamar men jadi karakter tertentu seperti pendeta, lorang tua, pengedar narkoba, atau petani. Untuk menghindari kecurigaan, penyamarannya selalu berubah-ubah.\n"+
                    "\t\tAntara tahun 1992 hingga 1999, Luis Garavito memangsa banyak sekali korban anak laki-laki di seluruh Kolombia tanpa sedikit pun merasa takut akan ditangkap. Saat tertangkap, barulah ia mengaku telah membunuh ratusan anak saat berkeliling 54 kota di negara tersebut. Fakta bahwa ia terus berkelana, menyamar, dan korbannya memang tidak akan dicari saat hilang, membuat ia selalu aman melakukan aksinya. Diperkirakan pembunuhan-pembunuhan tersebut ia lakukan di sekitar Pereira, daerah asalnya. Begitu calon korbannya kelelahan diajak berjalan jauh oleh Garavito, maka ia akan mulai mengikat, menyiksa dan memperkosanya. Kadang kemaluan mereka dipotong dan dimasukkan ke mulut si korban. Mayat-mayat mereka biasanya ditemukan di kuburan dangkal dengan beberapa bekas gigitan. Tempat Kejadian Perkara biasanya dipenuhi botol minuman keras dan pelumas. Setelah ditangkap, Garavito mengaku mabuk saat membunuhi mereka dan menyatakan bahwa tubuhnya dikuasai oleh \"sang penguasa\"\n"+
                    "\t\tAksi Garavito menjadi mulus karena Kolombia baru saja lepas dari Konflik Kolombia pada tahun 1964. Pada masa itu banyak anak-anak tanpa keluarga berkeliaran di jalan. Dengan kondisi sangat kelaparan dan baju compang-camping, nyaris tidak ada yang mempedulikan kalau mereka tiba-tiba menghilang.\n"+
                    "\t\tKejahatan Garavito mulai terkuak pada bulan November 1997, saat ditemukannya 25 tubuh anak-anak tak dikenal di Pereira di sebuah kuburan massal. Pada bulan Februari 1998, dua jenazah lainnya ditemukan bersebelahan di luar Kota Genoa di Kolombia. Satu lainnya ditemukan bersama senjata yang digunakan Garavito untuk membunuh. Polisi juga menemukan catatan di sekitar lokasi tersebut dengan petunjuk alamat yang membawa polisi kepada kekasih Garavito. Pada saat itu, ia mengaku sudah tujuh bulan tak bertemu Garavito, tapi kemudian menyerahkan barang-barang milik Garavito yang kemudian menjadi bukti, antara lain foto-foto anak lelaki, catatan pembunuhan, dan daftar panjang nama korbannya\n"+
                    "\t\tBukti perbuatan Garavito didapatkan dari kekasihnya. Polisi kemudian berhasil melacak tempat tinggal Garavito. Namun ia tak lagi tinggal di sana. Hanya saja, ia kemudian tidak beruntung lagi setelah diserang oleh seorang gelandangan. Gelandangan tersebut menyaksikan Garavito menyerang seorang anak jalanan dan berusaha membela anak tersebut. Ia tak sadar kalau yang dilawannya adalah seorang pembunuh tersadis sepanjang sejarah.\n"+
                    "\t\tLuis Garavito akhirnya ditangkap 22 April 1999. Namun polisi yang menahannya tidak sadar akan kekejaman Garavito. Tanpa disangka, perbuatannya kemudian tersingkap saat interogasi dan ia mengaku telah membunuh belasan anak. Bersama pengakuan tersebut, dan bukti-bukti DNA Garavito yang menempel di korban, serta kacamata yang tertinggal di TKP. Kacamata tersebut khusus dibuat untuk kerusakan mata yang dia alami."+
                    "\t\tPada akhirnya, Garavito mengakui perbuatannya membunuh 140 anak di Kolombia dan dituntut atas 172 pembunuhan. Ia terbukti bersalah untuk 138 tuntutan. Meskipun vonis yang ia dapat adalah 1.853 tahun penjara, hukum Kolombia membatasi penjara maksimal sepanjang 40 tahun (berdasarkan artikel 37.1 dari Colombian Penal Code). Karena ia bekerjasama dengan polisi menunjukkan lokasi dari tubuh korbannya, hukuannya diperingan menjadi 22 tahun. Ia harusnya bebas pada tahun 2021, namun hukum Kolombia juga menetapkan bahwa kejahatan terhadap anak-anak tidak layak diberikan keringanan. Ia diasingkan dari narapidana yang lain untuk menjaga keamanannya. Ia sangat paranoid dan takut orang lain berusaha meracuninya. Karena itu ia hanya makan makanan dari orang yang dipercaya",
            "\t\tLopez lahir pada tahun 1948 di Tolima, Kolombia, saat negara itu dalam kekacauan politik dan kejahatan merajalela. Dia adalah anak ketujuh dari 13 bersaudara. Ketika Lopez berumur delapan tahun, ibunya memergokinya menyentuh payudara adiknya, dan dia ditendang keluar dari rumah selamanya."+
                    "\t\tLopez menjadi pengemis di jalanan Kolombia kekerasan. Ia segera didekati oleh seorang pria yang bersimpati dengan situasi anak itu dan menawarkan rumah yang aman dan makanan untuk dimakan. Lopez, putus asa dan lapar, tidak ragu-ragu dan pergi dengan pria itu. Alih-alih pergi ke rumah yang nyaman, ia dibawa ke sebuah bangunan yang ditinggalkan dan berulang kali disodomi dan kembali ke jalan. Selama serangan itu, Lopez marah bersumpah ia akan melakukan hal yang sama.\n"+
                    "\t\tLopez yang kurang pendidikan dan keterampilan, bisa selamat di jalanan dengan mengemis dan melakukan pencurian kecil. Ia mulai maju ke pencurian mobil, dan ia dibayar cukup tinggi ketika ia menjual mobil curian. Dia ditangkap pada usia 18 untuk pencurian mobil dan dikirim ke penjara. Setelah beberapa hari berada di sana, ia diperkosa oleh empat tahanan. Kemarahan dan kemarahan yang ia alami sebagai seorang anak kembali lagi.\n"+
                    "\t\tPada tahun 1978, Lopez dibebaskan dari penjara, pindah ke Peru , dan mulai menculik dan membunuh gadis-gadis muda Peru. Dia tertangkap oleh sekelompok orang India dan disiksa, dikubur sampai ke leher di pasir namun kemudian dibebaskan dan dideportasi ke Ekuador. Bahkan setelah mengalami semua hal itu ia tidak berubah.\n"+
                    "\t\tPada bulan April 1980, banjir membuat 4 mayat menyembul ke permukaan. Polisi Ekuador menyadari ada dalang pembunuhan berantai di baliknya. Tak lama setelah banjir, Lopez tertangkap basah hendak menculik seorang gadis muda. Ia tidak mau diajak kerja sama, oleh karena itu kepolisian meminta bantuan imam lokal untuk berpakaian sebagai tahanan dan menempatkannya di sel yang sama dengan Lopez. Trik berhasil, ia dengan mudah berbagi cerita tentang kejahatan brutalnya.\n"+
                    "\t\tDia tidak pernah membunuh di malam hari karena dia tidak bisa melihat mata korbannya dan merasa, tanpa unsur itu, pembunuhan akan sia-sia.",
            "\t\tPopkov mengundurkan diri dari kepolisian pada 1998. Ini mengejutkan kolega-koleganya saat itu karena ia dinilai punya prospek karier yang bagus. Tak lama terkuak bahwa ia ikut dalam investigasi pembunuhan yang ia lakukan sendiri. \n"+
                    "\t\tKorban Popkov yang paling muda berusia 15 tahun. Jasad-jasad korbannya ditemukan di kayu-kayu pemakaman lokal atau pinggir jalan. Sebagian besar ditemukan dalam keadaan telanjang. Hasil otopsi menunjukkan mereka diperkosa sebelum dibunuh.\n"+
                    "\t\tPopkov kemudian dinyatakan menderita disfungsi ereksi hingga akhirnya menghentikan pembunuhan. Ia menggunakan senjata tajam sebagai alat untuk membunuh. Hanya dua orang yang diketahui selamat dari kejahatan Popkov. Mereka pun menderita luka serius.\n"+
                    "\t\tSecara umum, korban biasanya dalam perjalanan pulang dari bar atau restoran. Popkov menguntit mereka dengan mobilnya. Ia menawarkan tebengan pulang. Tak jarang ia menggunakan mobil polisi."+
                    "\t\tPopkov mengakui bahwa ia mulai membunuh perempuan setelah ia diselingkuhi istrinya. Sebuah kelompok investigasi khusus sudah dibentuk sejak 1998 untuk mengurusi kejahatan pembunuhan berantai."+
                    "\t\tNamun penyelidikan tidak efektif dan dimulai kembali pada 2000. Kasus yang tertunda dibuka kembali pada 2012. Sampel DNA yang tertinggal membawa pada penangkapan Popkov."+
                    "\t\tIa ditahan pada Juni 2012 di Vladivostok saat mencoba melarikan diri ke Cina. Selama interogasi, ia memberikan sampel ludahnya yang membuktikan ia pelaku. Popkov dinyatakan bersalah pada 2015 dan divonis hukuman penjara seumur hidup.",
            "\t\tDikarunia paras tampan dan pendidikan tinggi seyogyanya membuat seseorang bersyukur dan menjalani hidupnya dengan baik. Namun, tidak begitu yang terjadi pada Ted Bundy. Psikolog ganteng yang digemari banyak perempuan ini justru memanfaatkan kelebihannya untuk hal yang mengerikan dan tidak masuk akal. Tidak sekedar membunuh, ia justru menjadikan kepala-kepala manusia sebagai koleksi yang disayanginya.\n"+
                    "\t\tBundy kecil dinamai Theodore Robert Cowel, ia dilahirkan oleh seorang ibu tunggal. Karena dilahirkan di luar nikah, kakek dan neneknya mengaku bahwa Bundy adalah anak mereka dan ibunya dikenalkan sebagai kakaknya. Dan saat ibunya menikah denan Johnnie Bundy, barulah ia mengetahui kenyataan sesungguhnya. Setelah itu, Ted kemudian memakai nama belakang ayah tirinya.\n"+
                    "\t\tMengetahui wanita yang diyakini sebagai kakak perempuan ternyata ibu kandungnya, Bundy mulai mengalami mental breakdown. Bundy mulai berubah menjadi pendiam dan mengisolasi diri. Upaya ayah tirinya untuk mendekatkan Bundy dengan keluarganya dimentahkan. Bundy kecil tidak sudi bermain dengan saudara-saudaranya dan memilih sendiri. Besar dalam kebohongan membuat mentalnya benar-benar jatuh.\n"+
                    "\t\tMeski lebih sering terlihat diam, Bundy terlihat menonjol karena kecerdasan otaknya. Karenanya mudah saja bagi Bundy meraih sarjana psikologi di Universitas Washington pada 1972. Di universitas Bundy jatuh cinta pada gadis populer dan kaya bernama Stephanie Brooks. Dan sayangnya, Bundy dibuat kecewa lantaran perempuan itu mengakhiri hubungannya secara tiba-tiba dan menghilang begitu saja.\n"+
                    "\t\tBundy yang kecewa terobsesi untuk kaya dan membuat Brooks serta keluarganya menyesal. Akhirnya Bundy lebih giat kuliah dan mengambil pascasarjana di bidang hukum. Setelahnya, ia terjun ke dunia politik dan menjadi juru kampanye kharismatik untuk Partai Republik. Dan ketika kekayaan sudah dicapai, Bundy untuk kedua kalinya berkesempatan bertemu dengan Brooks dan menjalin cinta. Brooks pun yakin untuk menikah dengan Bundy. Namun di saat seperti itu, Bundy dengan sengaja meninggalkan Brooks seperti yang dilakukan wanita itu kepadanya.\n"+
                    "\t\tBalas dendam atas patah hati yang dilakukan Bundy terhadap Brooks memang melegakan untuk sementara waktu. Namun kemudian, ia merasakan amarah yang dilampiaskan pada perempuan-perempuan yang memiliki ciri-ciri fisik yang sama dengan Brooks. Sebanyak 30 pembunuhan yang diakui oleh Bundy, sebelum dibunuh semua korbannya dilecehkan dan diperkosa terlebih dulu.\n"+
                    "\t\tTidak hanya itu kondisi yang dialami korban, beberapa di antaranya sengaja dipenggal untuk diambil kepalanya. Penggalan kepala itu disimpan Bundy sebagai kenang-kenangan. Total ada sekitar 12 kepala wanita dalam pendingin yang ada di apartemen Bundy.\n"+
                    "\t\tKasus perkosaan dan pembunuhan berantai yang dilakuan Bundy cukup lama terungkap. Sebenarnya, sudah ada saksi mata yang mencurigai sosok Bundy sebagai pelakunya. Namun ketika itu polisi menghubungi dan menemui Bundy, mereka terkecoh oleh pesona ramah dan ketampanan Bundy. Polisi menganggap tidak mungkin sosok berlatarbelakang pendidikan psikologi menjadi tersangka pembunuhan berantai yang mengerikan.\n"+
                    "\t\tKharismati dan ketampanan Bundy jugalah yang membuatnya mudah saja memperdaya korban. Namun akhirnya identitas Bundy terungkap setelah ada seorang korban yang berhasil lolos dari tikamannya. Dan pada akhirnya, Bundy meninggal di atas kursi listrik di Penjara Raiford Florida."
    };
    private static String[] namaPembunuh = {
            "Ahmad Suradji",
            "Albert Fish",
            "Elizabeth Bathory",
            "Harold Shipman",
            "Javed Iqbal",
            "John Wayne",
            "Luis Gravito",
            "Pedro Alonso Lopez",
            "Mikhail Popkov",
            "Ted Bunndy"
    };

    private static  String[] bioPem ={
            "Tanggal Lahir = 12 Desember 1952 \nJumlah Korban = 42 Orang \nTuduhan = Pembunuhan \nMeninggal = 10 Juli 2008 \nPenyebab Kematian = Dihukum Mati Tembak",
            "Tanggal Lahir = 19 Mei 1870\nJumlah Korban = Terbukti 5, Diperkirakan 100+ \nTuduhan = Pedofilia dan Kanibalisme \nMeninggal = 16 Januari 1936 \nPenyebab Kematian = Dihukum Mati Melalui Kursi Listrik",
            "Tanggal Lahir = 7 Agustus 1560 \nJumlah Korban = Tidak Pasti, Diperkirakan 650 Orang \nTuduhan = Pembunuhan dan Meminum Darah Korban \nMeninggal = 21 Agustus 1614 \nPenyebab Kematian = Meninggal Ketika Di penjara",
            "Tanggal Lahir = 14 January 1946 \nJumlah Korban = 215-250 Orang \nTuduhan = Penyalahgunaan Profesi dan Pembunuhan \nMeninggal = 13 January 2004 \nPenyebab Kematian = Gantung Diri",
            "Tanggal Lahir = 1956 \nJumlah Korban = 100 \nTuduhan = Pedofilia dan pembunuhan \nMeninggal = 8 October 2001 \nPenyebab Kematian = Bunuh diri sebelum dieksekusi gantung",
            "Tanggal Lahir = 17 Maret 1942 \nJumlah Korban = 33 Remaja \nTuduhan = Penculikan, Perkosaan dan Pembunuhan \nMeninggal = 10 Mei 1993 \nPenyebab Kematian = Di Hukum melalui suntik mati",
            "Tanggal Lahir = 25 Januari 1957 \nJumlah Korban = Terkonfirmasi 138, Mengakui 300 \nTuduhan = Pemerkosaan dan pembunuhan berantai \nMeninggal = - \nPenyebab Kematian = -",
            "Tanggal Lahir = 8 Oktober 1948 \nJumlah Korban = Lebih dari 350 anak-anak \nTuduhan = Pedofilia dan pembunuhan berantai \nMeninggal = - \nPenyebab Kematian = -",
            "Tanggal Lahir = 7 Maret 1964 \nJumlah Korban = Terbukti 78, Mengakui 83 \nTuduhan = Pemerkosaan dan Pembunuhan Berantai \nMeninggal = - \nPenyebab Kematian = -",
            "Tanggal Lahir = 24 November 1946 \nJumlah Korban = Mengakui 30, Diperkirakan Lebih dari 100 Orang \nTuduhan = Pemerkosaan, Mutilasi dan Pembunuhan Berantai \nMeninggal = 24 Januari 1989 \nPenyebab Kematian = Dihukum Mati Melalui Kursi Listrik"
    };
    private static  int[] fotoKiller = {
            R.drawable.ahmad_sur,
            R.drawable.albert_fish,
            R.drawable.elizabeth_bath,
            R.drawable.harold_shipman,
            R.drawable.javed_iqbal,
            R.drawable.john_wayne,
            R.drawable.luis_garavito,
            R.drawable.pedro_alonso,
            R.drawable.mikhail_popkov,
            R.drawable.ted_bundy
    };

    static ArrayList<Killers> getListData(){
        ArrayList<Killers> list = new ArrayList<>();
        for (int pos=0; pos<namaPembunuh.length; pos++){
            Killers bunuh = new Killers();
            bunuh.setName(namaPembunuh[pos]);
            bunuh.setDetail(detailPem[pos]);
            bunuh.setPhoto(fotoKiller[pos]);
            bunuh.setBio(bioPem[pos]);
            list.add(bunuh);
        }
        return list;
    }
}
